server:
  port: 8080

spring:
  messages:
    basename: messages, errors
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        default_batch_fetch_size: 1000 # N+1 문제 관련 배치사이즈
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-id: _Ymbc8719odBfiC_6Gf8
            client-secret: fBOAxjRBLX
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname
          google:
            client-id: 54922705722-bord36gpq924li6n2ihohv2s4c1vgh6o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          github:
            client-id: 3631b99780777031d70a
            client-secret: 73a62eb56ce064850d72568b7fed4a2cf94eee6c
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response